name: basic_without_CypressCloud_parallel
on:
  push:
    branches:
      # - 'master'
      # - 'main'
      - 'features/**'
  pull_request:
    branches:
      # - 'master'
      # - 'main'
      - 'features/**'
  workflow_dispatch:
jobs:
  cypress-run:
    strategy:
      matrix:
        browsers: [chrome, edge]
    runs-on: ubuntu-22.04
    # container:
    #     image: cypress/browsers:latest
    #     options: --user 1001
    name: cross-browser testing-${{matrix.browsers}}
    # continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run in chrome
        uses: cypress-io/github-action@v6
        with:
          browser: ${{matrix.browsers}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: store screenshots
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots-${{matrix.browsers}}
          path: cypress/screenshots
          # 'warn' or 'error' are also available, defaults to `warn`
          if-no-files-found: ignore
      - name: store videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{matrix.browsers}}
          path: cypress/videos
          # 'warn' or 'error' are also available, defaults to `warn`
          if-no-files-found: ignore
